GET http://localhost:3000/info
# info Page

###

GET http://localhost:3002/api/persons/643c7f9e3249de17fc71c7bc
#api/person/:id

###

POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name" : "Luigi",
    "number":"2332-232-4343"
}