GET http://localhost:3000/info
# info Page

###

GET http://localhost:3002/api/persons/2
#api/person/:id

###

POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name" : "Luigi Bro",
    "number":"2332-232-4343"
}